### ISSUE TITLE
Support `streaming`

### ISSUE THREAD

**Issue by Twey** [capnproto/capnproto-rust#230] opened 2021-07-26 17:48 UTC
It seems that a file is missing from the `capnpc-rust` distribution to support the [`streaming` attribute](https://capnproto.org/news/2020-04-23-capnproto-0.8.html):
```
PS> capnp compile -orust --src-prefix=schema\\ schema\point.capnp
schema\\point.capnp:8:35-41: error: A method declaration uses streaming, but '/capnp/stream.capnp' is not found in the import path. This is a standard file that should always be installed with the Cap'n Proto compiler.
```

`point.capnp`:
```capnp
@0xdcaf678ef37b50f2;

interface MyInterface {
  streamingCall @0 (callback :Callback) -> ();

  interface Callback {
    # NEW: This streaming call features flow control!
    sendChunk @0 (chunk :Data) -> stream;
    done @1 ();
  }
}
```

**Comment by dwrensha** [comment] 2021-07-27 12:19
What happens if you do this?
```
capnp compile -orust --src-prefix=schema\\ schema\point.capnp
```
I expect that you'll get the same error. I think this means that your base capnproto-c++ installation is broken somehow.

How did you install the `capnp` executable?

Note, in any case, that capnproto-rust provides no special streaming support yet. You should be able to use methods that have the `stream` attribute, but the attribute will be ignored.

**Comment by dwrensha** [comment] 2021-07-27 12:20
EDIT I meant to ask: what happens if you do this?
```
capnp compile -ocapnp --src-prefix=schema\\ schema\point.capnp
```

**Comment by Twey** [comment] 2021-07-29 12:07
Yes, it produces the same error.
This Cap'n P was installed using the [official Windows instructions for Cap'n Proto installation](https://capnproto.org/install.html#installation-windows), not including the C++ bit (because, as the instructions say, if I don't want to use C++ I don't need to).  I think the implication is that each language's implementation is responsible for providing these files?  I see the `stream.capnp` in the official repo seems to include a C++-specific file.

**Comment by dwrensha** [comment] 2021-07-29 13:30
If you get the same error when doing `capnp compile -ocapnp`, then that means the problem is happening before anything having to do with Rust is involved.

I think probably the best solution will be for you to additionally copy the `stream.capnp` file (and maybe `c++.capnp` too) into your local installation, and make sure that `capnp compile` can find it (possibly through the `-I` flag). And probably the official Windows instructions should be updated to mention this.

**Comment by dwrensha** [comment] 2021-07-29 13:39
I opened https://github.com/capnproto/capnproto/issues/1288 upstream.

**Comment by dwrensha** [comment] 2021-08-08 23:10
Upstream documentation was fixed in https://github.com/capnproto/capnproto/commit/ac297669bcea3b9a62dc992001643a4e77de4b67

**Closed by dwrensha** 2021-08-08 23:10 UTC

**Comment by tamird** [comment] 2023-08-23 14:53
I'm seeing a related issue. How is one supposed to specify the location of so-called "well known" capnp files? Compiling my schema works:
```sh
$ capnpc  -ocapnp schema/ex.capnp  | grep stream
      sendChunk @0 (chunk :Data) -> stream;

```
but code generation fails here:
https://github.com/capnproto/capnproto-rust/blob/c702d16dd9c8b5acdf2ae8937c954171fb164d49/capnpc/src/lib.rs#L352-L358

my build.rs:
```rust
fn main() {
    capnpc::CompilerCommand::new()
        .src_prefix("schema")
        .file("schema/schema.capnp")
        .file("capnp/stream.capnp")
        .run()
        .expect("schema compiler command");
}
```

**Comment by dwrensha** [comment] 2023-08-23 22:24
@tamird possibly you need to specify an import path:

https://github.com/capnproto/capnproto-rust/blob/c702d16dd9c8b5acdf2ae8937c954171fb164d49/capnpc/src/lib.rs#L153-L161

(I don't expect this to be necessary if the capnp c++ library and headers are installed in a standard location, but maybe yours aren't?)

**Comment by tamird** [comment] 2023-08-23 22:31
@dwrensha I'm not sure how that would help. The failure happens in the rust code generator library before camp is invoked. How would an import path help?

**Comment by dwrensha** [comment] 2023-08-24 00:01
Ah, yes, that will not help. I opened a new issue: https://github.com/capnproto/capnproto-rust/issues/430

I think probably, for core schemas that come with the C++ distribution, we should include their generated Rust code in the base `capnp` crate.

Until then, you need to generate code for `streaming.capnp` yourself. Because this is not just an import -- it's actually full code generation -- you'll need to provide the full path in the `.file()` call. You might find it convenient to copy `streaming.capnp` into your own project's repo.
